
# Only available in ansible 2.x
#- name: configure trusted network
#  firewalld: source={{ mynetwork }} state=enabled

- name: Allow service mysql in firewall
  firewalld: service=mysql permanent=true state=enabled immediate=yes
